
services:
  frontend:
    restart: on-failure
    build: ./reactapp
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4002/tasks

  backend:
    restart: on-failure
    build: ./webapi
    container_name: backend
    ports:
      - '4000:80'
    environment:
      - Cors:AllowedOrigins=http://localhost:4002

  proxy:
    restart: on-failure
    build: ./nginx
    container_name: proxy
    ports:
      - '4002:8080'
    depends_on:
      - frontend
      - backend